window.CALCULATORS=[
{id:"porcentagem",slug:"porcentagem",icon:"%",cat:"math",type:"percentage",title:{pt:"Calculadora de porcentagem",en:"Percentage calculator",es:"Calculadora de porcentaje"},desc:{pt:"Calcule porcentagens, aumentos e reduções.",en:"Calculate percentages, increases and reductions.",es:"Calcula porcentajes, aumentos y reducciones."}},
{id:"regra-de-tres",slug:"regra-de-tres",icon:"⅓",cat:"math",type:"rule3",title:{pt:"Regra de três",en:"Rule of three",es:"Regla de tres"},desc:{pt:"Resolva proporções de forma rápida.",en:"Solve proportions quickly.",es:"Resuelve proporciones rápidamente."}},
{id:"media",slug:"media",icon:"x̄",cat:"math",type:"average",title:{pt:"Média aritmética",en:"Arithmetic mean",es:"Media aritmética"},desc:{pt:"Calcule a média de vários números.",en:"Calculate the average of several numbers.",es:"Calcula la media de varios números."}},
{id:"soma",slug:"soma",icon:"Σ",cat:"math",type:"sum",title:{pt:"Soma de números",en:"Number sum",es:"Suma de números"},desc:{pt:"Some vários valores rapidamente.",en:"Add several values quickly.",es:"Suma varios valores rápidamente."}},
{id:"juros-simples",slug:"juros-simples",icon:"%",cat:"finance",type:"simpleInterest",title:{pt:"Juros simples",en:"Simple interest",es:"Interés simple"},desc:{pt:"Calcule juros e montante.",en:"Calculate simple interest and total.",es:"Calcula interés simple y monto."}},
{id:"juros-compostos",slug:"juros-compostos",icon:"↗",cat:"finance",type:"compoundInterest",title:{pt:"Calculadora de juros compostos",en:"Compound interest calculator",es:"Calculadora de interés compuesto"},desc:{pt:"Calcule juros, montante e crescimento do dinheiro ao longo do tempo.",en:"Calculate interest, future value and growth over time.",es:"Calcula intereses, monto y crecimiento a lo largo del tiempo."}},
{id:"financiamento",slug:"financiamento",icon:"🏦",cat:"finance",type:"loan",title:{pt:"Calculadora de financiamento",en:"Loan payment calculator",es:"Calculadora de financiación"},desc:{pt:"Calcule a parcela, os juros e o custo total de um financiamento.",en:"Estimate loan payments, interest and total cost.",es:"Calcula la cuota, los intereses y el costo total de una financiación."}},
{id:"desconto",slug:"desconto",icon:"🏷️",cat:"finance",type:"discount",title:{pt:"Calculadora de desconto",en:"Discount calculator",es:"Calculadora de descuento"},desc:{pt:"Descubra o preço final e a economia.",en:"Find final price and savings.",es:"Calcula precio final y ahorro."}},
{id:"aumento-percentual",slug:"aumento-percentual",icon:"↗",cat:"finance",type:"increase",title:{pt:"Aumento percentual",en:"Percentage increase",es:"Aumento porcentual"},desc:{pt:"Calcule o aumento entre dois valores.",en:"Calculate the increase between values.",es:"Calcula el aumento entre valores."}},
{id:"margem-de-lucro",slug:"margem-de-lucro",icon:"📈",cat:"business",type:"margin",title:{pt:"Margem de lucro",en:"Profit margin",es:"Margen de beneficio"},desc:{pt:"Calcule lucro e margem de venda.",en:"Calculate profit and sales margin.",es:"Calcula beneficio y margen."}},
{id:"markup",slug:"markup",icon:"🏷️",cat:"business",type:"markup",title:{pt:"Markup",en:"Markup",es:"Markup"},desc:{pt:"Descubra preço de venda a partir do custo.",en:"Find selling price from cost.",es:"Calcula precio de venta desde el costo."}},
{id:"ponto-de-equilibrio",slug:"ponto-de-equilibrio",icon:"⚖️",cat:"business",type:"breakEven",title:{pt:"Ponto de equilíbrio",en:"Break-even point",es:"Punto de equilibrio"},desc:{pt:"Estime quanto vender para cobrir custos.",en:"Estimate sales needed to cover costs.",es:"Estima ventas para cubrir costos."}},
{id:"comissao",slug:"comissao",icon:"💼",cat:"business",type:"commission",title:{pt:"Comissão de vendas",en:"Sales commission",es:"Comisión de ventas"},desc:{pt:"Calcule comissão sobre vendas.",en:"Calculate sales commission.",es:"Calcula comisión sobre ventas."}},
{id:"salario-liquido",slug:"salario-liquido",icon:"💼",cat:"work",type:"netSalary",title:{pt:"Calculadora de salário líquido",en:"Net salary calculator",es:"Calculadora de salario neto"},desc:{pt:"Calcule uma estimativa do salário líquido a partir do salário bruto e dos descontos.",en:"Estimate net salary from gross pay and deductions.",es:"Calcula una estimación del salario neto a partir del salario bruto y los descuentos."}},
{id:"ferias",slug:"ferias",icon:"🏖️",cat:"work",type:"vacation",title:{pt:"Calculadora de férias",en:"Vacation pay calculator",es:"Calculadora de vacaciones"},desc:{pt:"Calcule uma estimativa das férias com adicional de 1/3 do salário.",en:"Estimate vacation pay including the one-third bonus.",es:"Calcula una estimación de las vacaciones con el tercio adicional."}},
{id:"decimo-terceiro",slug:"decimo-terceiro",icon:"🎁",cat:"work",type:"thirteenth",title:{pt:"13º salário",en:"13th salary",es:"13.º salario"},desc:{pt:"Estime o 13º proporcional aos meses trabalhados.",en:"Estimate a proportional 13th salary.",es:"Estima el salario 13 proporcional."}},
{id:"horas-extras",slug:"horas-extras",icon:"⏱️",cat:"work",type:"overtime",title:{pt:"Horas extras",en:"Overtime calculator",es:"Horas extra"},desc:{pt:"Estime o valor de horas extras.",en:"Estimate overtime pay.",es:"Estima el pago de horas extra."}},
{id:"fgts",slug:"fgts",icon:"🏦",cat:"work",type:"fgts",title:{pt:"FGTS — estimativa",en:"FGTS estimate",es:"Estimación FGTS"},desc:{pt:"Estime o depósito mensal de FGTS a partir do salário.",en:"Estimate monthly FGTS deposit from salary.",es:"Estima el depósito mensual de FGTS."}},
{id:"rescisao",slug:"rescisao",icon:"📄",cat:"work",type:"termination",title:{pt:"Calculadora de rescisão trabalhista",en:"Employment termination calculator",es:"Calculadora de liquidación laboral"},desc:{pt:"Estime saldo de salário, férias, 13º, aviso prévio, FGTS e outras verbas de rescisão.",en:"Estimate salary balance, vacation pay, 13th salary, notice, FGTS and other termination amounts.",es:"Estima salario pendiente, vacaciones, paga extra, preaviso y otras cantidades de liquidación."}},
{id:"escala-12x36",slug:"escala-12x36",icon:"🔄",cat:"work",type:"shift",title:{pt:"Escala 12x36",en:"12x36 shift",es:"Turno 12x36"},desc:{pt:"Calcule dias trabalhados em uma escala 12x36.",en:"Calculate work days on a 12x36 shift.",es:"Calcula días trabajados en turno 12x36."}},
{id:"combustivel",slug:"combustivel",icon:"⛽",cat:"daily",type:"fuel",title:{pt:"Calculadora de combustível",en:"Fuel cost calculator",es:"Calculadora de combustible"},desc:{pt:"Calcule consumo, litros e custo de combustível para uma viagem.",en:"Calculate fuel consumption, liters and trip cost.",es:"Calcula consumo, litros y costo de combustible para un viaje."}},
{id:"dividir-conta",slug:"dividir-conta",icon:"🍽️",cat:"daily",type:"splitBill",title:{pt:"Dividir conta",en:"Split bill",es:"Dividir cuenta"},desc:{pt:"Divida uma conta entre pessoas e inclua gorjeta.",en:"Split a bill between people with a tip.",es:"Divide una cuenta entre personas."}},
{id:"gorjeta",slug:"gorjeta",icon:"💵",cat:"daily",type:"tip",title:{pt:"Gorjeta",en:"Tip calculator",es:"Propina"},desc:{pt:"Calcule gorjeta e total da conta.",en:"Calculate tip and total.",es:"Calcula propina y total."}},
{id:"conversor-de-unidades",slug:"conversor-de-unidades",icon:"↔",cat:"daily",type:"units",title:{pt:"Conversor de unidades",en:"Unit converter",es:"Conversor de unidades"},desc:{pt:"Converta comprimento, peso e temperatura.",en:"Convert length, weight and temperature.",es:"Convierte longitud, peso y temperatura."}},
{id:"velocidade",slug:"velocidade",icon:"🚗",cat:"daily",type:"speed",title:{pt:"Velocidade média",en:"Average speed",es:"Velocidad media"},desc:{pt:"Calcule velocidade média.",en:"Calculate average speed.",es:"Calcula velocidad media."}},
{id:"ritmo-corrida",slug:"ritmo-corrida",icon:"🏃",cat:"daily",type:"pace",title:{pt:"Ritmo de corrida",en:"Running pace",es:"Ritmo de carrera"},desc:{pt:"Calcule seu ritmo médio por quilômetro.",en:"Calculate average running pace.",es:"Calcula ritmo medio por kilómetro."}},
{id:"imc",slug:"imc",icon:"⚖️",cat:"health",type:"bmi",title:{pt:"IMC",en:"BMI",es:"IMC"},desc:{pt:"Calcule o índice de massa corporal.",en:"Calculate body mass index.",es:"Calcula el índice de masa corporal."}},
{id:"calorias",slug:"calorias",icon:"🔥",cat:"health",type:"calories",title:{pt:"Calorias — estimativa",en:"Calories estimate",es:"Estimación de calorías"},desc:{pt:"Estime calorias de manutenção usando uma fórmula básica.",en:"Estimate maintenance calories with a basic formula.",es:"Estima calorías de mantenimiento."}},
{id:"idade",slug:"idade",icon:"🎂",cat:"date",type:"age",title:{pt:"Calculadora de idade",en:"Age calculator",es:"Calculadora de edad"},desc:{pt:"Calcule sua idade em anos.",en:"Calculate your age in years.",es:"Calcula tu edad en años."}},
{id:"dias-de-vida",slug:"dias-de-vida",icon:"⌛",cat:"date",type:"daysAlive",title:{pt:"Dias de vida",en:"Days alive",es:"Días de vida"},desc:{pt:"Estime quantos dias você viveu.",en:"Estimate how many days you have lived.",es:"Estima cuántos días has vivido."}},
{id:"diferenca-entre-datas",slug:"diferenca-entre-datas",icon:"📅",cat:"date",type:"dateDiff",title:{pt:"Diferença entre datas",en:"Date difference",es:"Diferencia entre fechas"},desc:{pt:"Veja quantos dias existem entre duas datas.",en:"Find the days between two dates.",es:"Calcula días entre dos fechas."}},
{id:"dias-uteis",slug:"dias-uteis",icon:"🗓️",cat:"date",type:"businessDays",title:{pt:"Dias úteis",en:"Business days",es:"Días laborables"},desc:{pt:"Conte dias úteis entre duas datas, sem feriados.",en:"Count weekdays between two dates, excluding holidays.",es:"Cuenta días laborables sin festivos."}},
{id:"data-final",slug:"data-final",icon:"📆",cat:"date",type:"addDays",title:{pt:"Adicionar dias a uma data",en:"Add days to a date",es:"Añadir días a una fecha"},desc:{pt:"Descubra a data depois de adicionar dias.",en:"Find the date after adding days.",es:"Calcula una fecha después de añadir días."}},
{id:"area",slug:"area",icon:"▣",cat:"math",type:"area",title:{pt:"Área de retângulo",en:"Rectangle area",es:"Área de rectángulo"},desc:{pt:"Calcule área a partir de largura e altura.",en:"Calculate area from width and height.",es:"Calcula área con ancho y alto."}},
{id:"volume",slug:"volume",icon:"◫",cat:"math",type:"volume",title:{pt:"Volume de caixa",en:"Box volume",es:"Volumen de caja"},desc:{pt:"Calcule o volume de uma caixa.",en:"Calculate box volume.",es:"Calcula el volumen de una caja."}},
{id:"conversao-temperatura",slug:"conversao-temperatura",icon:"🌡️",cat:"math",type:"temperature",title:{pt:"Conversão de temperatura",en:"Temperature converter",es:"Conversor de temperatura"},desc:{pt:"Converta Celsius, Fahrenheit e Kelvin.",en:"Convert Celsius, Fahrenheit and Kelvin.",es:"Convierte Celsius, Fahrenheit y Kelvin."}},
{id:"conversao-moeda",slug:"conversao-moeda",icon:"💱",cat:"finance",type:"currency",title:{pt:"Conversor de moeda",en:"Currency converter",es:"Conversor de moneda"},desc:{pt:"Converta moedas usando uma taxa informada por você.",en:"Convert currencies using a rate you provide.",es:"Convierte monedas usando una tasa que indiques."}},
{id:"inflacao",slug:"inflacao",icon:"📊",cat:"finance",type:"inflation",title:{pt:"Inflação acumulada",en:"Cumulative inflation",es:"Inflación acumulada"},desc:{pt:"Calcule inflação acumulada de várias taxas.",en:"Calculate cumulative inflation from several rates.",es:"Calcula inflación acumulada."}},
{id:"comissao-percentual",slug:"comissao-percentual",icon:"💰",cat:"business",type:"commission",title:{pt:"Comissão percentual",en:"Percentage commission",es:"Comisión porcentual"},desc:{pt:"Calcule comissão a partir do valor vendido.",en:"Calculate commission from sales.",es:"Calcula comisión sobre ventas."}},
{id:"custo-por-unidade",slug:"custo-por-unidade",icon:"📦",cat:"business",type:"unitCost",title:{pt:"Custo por unidade",en:"Unit cost",es:"Costo por unidad"},desc:{pt:"Descubra o custo médio por unidade.",en:"Find average cost per unit.",es:"Calcula costo por unidad."}},
{id:"ponto-de-reposicao",slug:"ponto-de-reposicao",icon:"📦",cat:"business",type:"reorder",title:{pt:"Ponto de reposição",en:"Reorder point",es:"Punto de reposición"},desc:{pt:"Estime estoque mínimo com consumo e prazo.",en:"Estimate reorder point from usage and lead time.",es:"Estima punto de reposición."}},
{id:"conversao-peso",slug:"conversao-peso",icon:"⚖️",cat:"daily",type:"weight",title:{pt:"Conversor de peso",en:"Weight converter",es:"Conversor de peso"},desc:{pt:"Converta kg, g, lb e oz.",en:"Convert kg, g, lb and oz.",es:"Convierte kg, g, lb y oz."}},
{id:"conversao-comprimento",slug:"conversao-comprimento",icon:"📏",cat:"daily",type:"length",title:{pt:"Conversor de comprimento",en:"Length converter",es:"Conversor de longitud"},desc:{pt:"Converta metros, quilômetros, pés e milhas.",en:"Convert meters, kilometers, feet and miles.",es:"Convierte metros, kilómetros, pies y millas."}},
{id:"conversao-area",slug:"conversao-area",icon:"▧",cat:"daily",type:"areaConvert",title:{pt:"Conversor de área",en:"Area converter",es:"Conversor de área"},desc:{pt:"Converta m², km², hectares e acres.",en:"Convert square units, hectares and acres.",es:"Convierte unidades de área."}},
{id:"conversao-volume",slug:"conversao-volume",icon:"🧪",cat:"daily",type:"volumeConvert",title:{pt:"Conversor de volume",en:"Volume converter",es:"Conversor de volumen"},desc:{pt:"Converta litros, ml, m³ e galões.",en:"Convert liters, ml, cubic meters and gallons.",es:"Convierte litros, ml, m³ y galones."}},
{id:"preco-com-desconto",slug:"preco-com-desconto",icon:"🛒",cat:"daily",type:"discount",title:{pt:"Preço com desconto",en:"Sale price",es:"Precio con descuento"},desc:{pt:"Descubra quanto você paga depois do desconto.",en:"Find the price after discount.",es:"Calcula el precio con descuento."}},
{id:"regra-de-porcentagem",slug:"regra-de-porcentagem",icon:"%",cat:"math",type:"percentage",title:{pt:"Quanto é X% de Y?",en:"What is X% of Y?",es:"¿Cuánto es X% de Y?"},desc:{pt:"Descubra rapidamente uma porcentagem de um valor.",en:"Quickly find a percentage of a value.",es:"Calcula rápidamente un porcentaje."}},
{id:"juros-por-mes",slug:"juros-por-mes",icon:"📈",cat:"finance",type:"compoundInterest",title:{pt:"Juros por mês",en:"Monthly interest",es:"Interés mensual"},desc:{pt:"Simule crescimento mensal com juros compostos.",en:"Simulate monthly compound growth.",es:"Simula crecimiento mensual compuesto."}}
,{id:"porcentagem-de-aumento",slug:"porcentagem-de-aumento",icon:"%",cat:"math",type:"increase",title:{pt:"Porcentagem de aumento",en:"Percentage increase",es:"Aumento porcentual"},desc:{pt:"Calcule quanto um valor aumentou.",en:"Calculate percentage increase.",es:"Calcula el aumento porcentual."}}
,{id:"porcentagem-de-reducao",slug:"porcentagem-de-reducao",icon:"%",cat:"math",type:"discount",title:{pt:"Porcentagem de redução",en:"Percentage reduction",es:"Reducción porcentual"},desc:{pt:"Calcule a redução percentual.",en:"Calculate percentage reduction.",es:"Calcula la reducción porcentual."}}
,{id:"regra-de-tres-inversa",slug:"regra-de-tres-inversa",icon:"⅓",cat:"math",type:"rule3",title:{pt:"Regra de três inversa",en:"Inverse rule of three",es:"Regla de tres inversa"},desc:{pt:"Resolva uma proporção inversa.",en:"Solve an inverse proportion.",es:"Resuelve una proporción inversa."}}
,{id:"proporcao",slug:"proporcao",icon:"∝",cat:"math",type:"rule3",title:{pt:"Calculadora de proporção",en:"Ratio calculator",es:"Calculadora de proporciones"},desc:{pt:"Calcule relações e proporções.",en:"Calculate ratios and proportions.",es:"Calcula relaciones y proporciones."}}
,{id:"media-ponderada",slug:"media-ponderada",icon:"x̄",cat:"math",type:"average",title:{pt:"Média ponderada",en:"Weighted average",es:"Media ponderada"},desc:{pt:"Calcule uma média.",en:"Calculate an average.",es:"Calcula una media."}}
,{id:"juros-diarios",slug:"juros-diarios",icon:"📈",cat:"finance",type:"compoundInterest",title:{pt:"Juros diários",en:"Daily interest",es:"Interés diario"},desc:{pt:"Simule crescimento composto.",en:"Simulate compound growth.",es:"Simula crecimiento compuesto."}}
,{id:"juros-anuais",slug:"juros-anuais",icon:"📈",cat:"finance",type:"compoundInterest",title:{pt:"Juros anuais",en:"Annual interest",es:"Interés anual"},desc:{pt:"Calcule crescimento anual.",en:"Calculate annual growth.",es:"Calcula crecimiento anual."}}
,{id:"montante",slug:"montante",icon:"💰",cat:"finance",type:"compoundInterest",title:{pt:"Calculadora de montante",en:"Future value calculator",es:"Calculadora de monto"},desc:{pt:"Calcule o valor acumulado.",en:"Calculate accumulated value.",es:"Calcula valor acumulado."}}
,{id:"rentabilidade",slug:"rentabilidade",icon:"📊",cat:"finance",type:"increase",title:{pt:"Calculadora de rentabilidade",en:"Return calculator",es:"Calculadora de rentabilidad"},desc:{pt:"Calcule retorno percentual.",en:"Calculate percentage return.",es:"Calcula retorno porcentual."}}
,{id:"preco-venda",slug:"preco-venda",icon:"🏷️",cat:"business",type:"markup",title:{pt:"Calculadora de preço de venda",en:"Selling price calculator",es:"Calculadora de precio de venta"},desc:{pt:"Calcule preço de venda a partir do custo.",en:"Calculate selling price from cost.",es:"Calcula precio de venta."}}

,{id:"lucro-bruto",slug:"lucro-bruto",icon:"📈",cat:"business",type:"margin",title:{pt:"Calculadora de lucro bruto",en:"Gross profit calculator",es:"Calculadora de beneficio bruto"},desc:{pt:"Calcule lucro e margem.",en:"Calculate profit and margin.",es:"Calcula beneficio y margen."}}
,{id:"comissao-vendedor",slug:"comissao-vendedor",icon:"💼",cat:"business",type:"commission",title:{pt:"Comissão de vendedor",en:"Salesperson commission",es:"Comisión de vendedor"},desc:{pt:"Calcule comissão sobre vendas.",en:"Calculate sales commission.",es:"Calcula comisión sobre ventas."}}
,{id:"custo-medio",slug:"custo-medio",icon:"📦",cat:"business",type:"unitCost",title:{pt:"Custo médio",en:"Average cost",es:"Costo medio"},desc:{pt:"Calcule custo médio por unidade.",en:"Calculate average unit cost.",es:"Calcula costo medio."}}
,{id:"estoque-minimo",slug:"estoque-minimo",icon:"📦",cat:"business",type:"reorder",title:{pt:"Estoque mínimo",en:"Minimum stock",es:"Stock mínimo"},desc:{pt:"Estime estoque mínimo.",en:"Estimate minimum stock.",es:"Estima stock mínimo."}}
,{id:"salario-por-hora",slug:"salario-por-hora",icon:"💼",cat:"work",type:"overtime",title:{pt:"Salário por hora",en:"Hourly pay",es:"Salario por hora"},desc:{pt:"Estime o valor da hora.",en:"Estimate hourly pay.",es:"Estima valor por hora."}}
,{id:"salario-por-dia",slug:"salario-por-dia",icon:"💼",cat:"work",type:"netSalary",title:{pt:"Salário por dia",en:"Daily pay",es:"Salario por día"},desc:{pt:"Estime um valor diário.",en:"Estimate daily pay.",es:"Estima salario diario."}}
,{id:"ferias-proporcionais",slug:"ferias-proporcionais",icon:"🏖️",cat:"work",type:"vacation",title:{pt:"Férias proporcionais",en:"Proportional vacation",es:"Vacaciones proporcionales"},desc:{pt:"Estime férias proporcionais.",en:"Estimate proportional vacation pay.",es:"Estima vacaciones proporcionales."}}
,{id:"decimo-terceiro-proporcional",slug:"decimo-terceiro-proporcional",icon:"🎁",cat:"work",type:"thirteenth",title:{pt:"13º proporcional",en:"Proportional 13th salary",es:"13.º proporcional"},desc:{pt:"Estime o 13º proporcional.",en:"Estimate proportional 13th salary.",es:"Estima el salario 13 proporcional."}}
,{id:"adicional-hora-extra",slug:"adicional-hora-extra",icon:"⏱️",cat:"work",type:"overtime",title:{pt:"Adicional de hora extra",en:"Overtime premium",es:"Adicional de horas extra"},desc:{pt:"Calcule horas com adicional.",en:"Calculate overtime with a premium.",es:"Calcula horas extra con adicional."}}
,{id:"combustivel-por-km",slug:"combustivel-por-km",icon:"⛽",cat:"daily",type:"fuel",title:{pt:"Custo de combustível por km",en:"Fuel cost per km",es:"Costo de combustible por km"},desc:{pt:"Estime custo por quilômetro.",en:"Estimate fuel cost per kilometer.",es:"Estima costo por kilómetro."}}

,{id:"autonomia",slug:"autonomia",icon:"⛽",cat:"daily",type:"fuel",title:{pt:"Autonomia do carro",en:"Car range calculator",es:"Autonomía del coche"},desc:{pt:"Estime a autonomia do veículo.",en:"Estimate vehicle range.",es:"Estima autonomía."}}
,{id:"custo-viagem",slug:"custo-viagem",icon:"🚗",cat:"daily",type:"fuel",title:{pt:"Custo de viagem",en:"Trip cost",es:"Costo de viaje"},desc:{pt:"Estime o gasto de combustível.",en:"Estimate trip fuel cost.",es:"Estima costo de viaje."}}
,{id:"tempo-de-viagem",slug:"tempo-de-viagem",icon:"🛣️",cat:"daily",type:"speed",title:{pt:"Tempo de viagem",en:"Travel time",es:"Tiempo de viaje"},desc:{pt:"Estime tempo de viagem.",en:"Estimate travel time.",es:"Estima tiempo de viaje."}}
,{id:"conversor-km-milhas",slug:"conversor-km-milhas",icon:"↔",cat:"daily",type:"length",title:{pt:"Conversor km para milhas",en:"Km to miles converter",es:"Conversor km a millas"},desc:{pt:"Converta quilômetros e milhas.",en:"Convert kilometers and miles.",es:"Convierte kilómetros y millas."}}
,{id:"conversor-kg-libras",slug:"conversor-kg-libras",icon:"⚖️",cat:"daily",type:"weight",title:{pt:"Conversor kg para libras",en:"Kg to pounds converter",es:"Conversor kg a libras"},desc:{pt:"Converta quilogramas e libras.",en:"Convert kilograms and pounds.",es:"Convierte kilogramos y libras."}}
,{id:"celsius-fahrenheit",slug:"celsius-fahrenheit",icon:"🌡️",cat:"daily",type:"temperature",title:{pt:"Celsius para Fahrenheit",en:"Celsius to Fahrenheit",es:"Celsius a Fahrenheit"},desc:{pt:"Converta temperaturas.",en:"Convert temperatures.",es:"Convierte temperaturas."}}
,{id:"metros-pes",slug:"metros-pes",icon:"📏",cat:"daily",type:"length",title:{pt:"Metros para pés",en:"Meters to feet",es:"Metros a pies"},desc:{pt:"Converta metros e pés.",en:"Convert meters and feet.",es:"Convierte metros y pies."}}
,{id:"dias-entre-datas",slug:"dias-entre-datas",icon:"📅",cat:"date",type:"dateDiff",title:{pt:"Quantos dias entre duas datas?",en:"Days between dates",es:"Días entre fechas"},desc:{pt:"Calcule dias entre datas.",en:"Calculate days between dates.",es:"Calcula días entre fechas."}}
,{id:"contagem-regressiva-dias",slug:"contagem-regressiva-dias",icon:"⏳",cat:"date",type:"dateDiff",title:{pt:"Contagem de dias",en:"Day countdown",es:"Cuenta de días"},desc:{pt:"Calcule a diferença entre datas.",en:"Calculate the difference between dates.",es:"Calcula la diferencia entre fechas."}}
,{id:"data-de-vencimento",slug:"data-de-vencimento",icon:"📆",cat:"date",type:"addDays",title:{pt:"Calculadora de vencimento",en:"Due date calculator",es:"Calculadora de vencimiento"},desc:{pt:"Encontre uma data adicionando dias.",en:"Find a due date by adding days.",es:"Calcula una fecha de vencimiento."}}

,{id:"idade-em-dias",slug:"idade-em-dias",icon:"⌛",cat:"date",type:"daysAlive",title:{pt:"Idade em dias",en:"Age in days",es:"Edad en días"},desc:{pt:"Estime a quantidade de dias vividos.",en:"Estimate days lived.",es:"Estima días vividos."}}
,{id:"calculadora-de-area",slug:"calculadora-de-area",icon:"▣",cat:"math",type:"area",title:{pt:"Calculadora de área",en:"Area calculator",es:"Calculadora de área"},desc:{pt:"Calcule área de um retângulo.",en:"Calculate rectangle area.",es:"Calcula área de un rectángulo."}}
,{id:"calculadora-de-volume",slug:"calculadora-de-volume",icon:"◫",cat:"math",type:"volume",title:{pt:"Calculadora de volume",en:"Volume calculator",es:"Calculadora de volumen"},desc:{pt:"Calcule volume de uma caixa.",en:"Calculate box volume.",es:"Calcula volumen de una caja."}}
,{id:"economia-no-desconto",slug:"economia-no-desconto",icon:"💰",cat:"finance",type:"discount",title:{pt:"Economia no desconto",en:"Discount savings",es:"Ahorro por descuento"},desc:{pt:"Veja quanto economiza.",en:"See how much you save.",es:"Calcula cuánto ahorras."}}
,{id:"preco-final",slug:"preco-final",icon:"🛒",cat:"finance",type:"discount",title:{pt:"Preço final",en:"Final price",es:"Precio final"},desc:{pt:"Calcule preço final após redução.",en:"Calculate final price after reduction.",es:"Calcula precio final."}}
,{id:"crescimento-percentual",slug:"crescimento-percentual",icon:"📈",cat:"finance",type:"increase",title:{pt:"Crescimento percentual",en:"Percentage growth",es:"Crecimiento porcentual"},desc:{pt:"Calcule crescimento entre valores.",en:"Calculate growth between values.",es:"Calcula crecimiento."}}
,{id:"investimento-inicial",slug:"investimento-inicial",icon:"💰",cat:"finance",type:"compoundInterest",title:{pt:"Investimento — estimativa",en:"Investment estimate",es:"Estimación de inversión"},desc:{pt:"Simule crescimento de um valor.",en:"Simulate investment growth.",es:"Simula crecimiento de una inversión."}}
,{id:"economia-combustivel",slug:"economia-combustivel",icon:"⛽",cat:"daily",type:"fuel",title:{pt:"Economia de combustível",en:"Fuel economy",es:"Ahorro de combustible"},desc:{pt:"Estime economia e custo.",en:"Estimate fuel economy and cost.",es:"Estima economía y costo."}}
,{id:"meta-de-vendas",slug:"meta-de-vendas",icon:"🎯",cat:"business",type:"breakEven",title:{pt:"Meta de vendas",en:"Sales target",es:"Meta de ventas"},desc:{pt:"Estime unidades para uma meta.",en:"Estimate units needed for a target.",es:"Estima unidades necesarias."}}
,{id:"preco-com-margem",slug:"preco-com-margem",icon:"🏷️",cat:"business",type:"markup",title:{pt:"Preço com margem",en:"Price with margin",es:"Precio con margen"},desc:{pt:"Calcule preço a partir do custo.",en:"Calculate price from cost.",es:"Calcula precio desde el costo."}}

,{id:"custo-mensal",slug:"custo-mensal",icon:"📊",cat:"business",type:"unitCost",title:{pt:"Custo mensal",en:"Monthly cost",es:"Costo mensual"},desc:{pt:"Calcule custo médio recorrente.",en:"Calculate average recurring cost.",es:"Calcula costo medio."}}
,{id:"estoque-seguranca",slug:"estoque-seguranca",icon:"📦",cat:"business",type:"reorder",title:{pt:"Estoque de segurança",en:"Safety stock",es:"Stock de seguridad"},desc:{pt:"Estime estoque adicional.",en:"Estimate safety stock.",es:"Estima stock de seguridad."}}
,{id:"comissao-mensal",slug:"comissao-mensal",icon:"💼",cat:"business",type:"commission",title:{pt:"Comissão mensal",en:"Monthly commission",es:"Comisión mensual"},desc:{pt:"Calcule comissão sobre vendas do mês.",en:"Calculate monthly sales commission.",es:"Calcula comisión mensual."}}
,{id:"renda-extra",slug:"renda-extra",icon:"💰",cat:"business",type:"increase",title:{pt:"Meta de renda extra",en:"Extra income target",es:"Meta de ingreso extra"},desc:{pt:"Calcule crescimento até uma meta.",en:"Calculate growth toward a target.",es:"Calcula crecimiento hacia una meta."}}
,{id:"preco-por-litro",slug:"preco-por-litro",icon:"⛽",cat:"daily",type:"unitCost",title:{pt:"Preço por litro",en:"Price per liter",es:"Precio por litro"},desc:{pt:"Calcule custo por volume.",en:"Calculate unit cost by volume.",es:"Calcula costo por volumen."}}
,{id:"consumo-medio",slug:"consumo-medio",icon:"⛽",cat:"daily",type:"fuel",title:{pt:"Consumo médio do veículo",en:"Average vehicle consumption",es:"Consumo medio del vehículo"},desc:{pt:"Estime consumo e custo.",en:"Estimate vehicle consumption and cost.",es:"Estima consumo y costo."}}
,{id:"litros-por-km",slug:"litros-por-km",icon:"⛽",cat:"daily",type:"fuel",title:{pt:"Litros por quilômetro",en:"Liters per kilometer",es:"Litros por kilómetro"},desc:{pt:"Estime consumo de combustível.",en:"Estimate fuel consumption.",es:"Estima consumo de combustible."}}
,{id:"conversor-litros-galoes",slug:"conversor-litros-galoes",icon:"🧪",cat:"daily",type:"volumeConvert",title:{pt:"Litros para galões",en:"Liters to gallons",es:"Litros a galones"},desc:{pt:"Converta litros e volume.",en:"Convert liters and volume.",es:"Convierte litros y volumen."}}
,{id:"conversor-hectares",slug:"conversor-hectares",icon:"🌾",cat:"daily",type:"areaConvert",title:{pt:"Conversor de hectares",en:"Hectare converter",es:"Conversor de hectáreas"},desc:{pt:"Converta unidades de área.",en:"Convert area units.",es:"Convierte unidades de área."}}
,{id:"data-futura",slug:"data-futura",icon:"📆",cat:"date",type:"addDays",title:{pt:"Calculadora de data futura",en:"Future date calculator",es:"Calculadora de fecha futura"},desc:{pt:"Descubra uma data no futuro.",en:"Find a future date.",es:"Calcula una fecha futura."}}
,{id:"dias-de-trabalho",slug:"dias-de-trabalho",icon:"🗓️",cat:"date",type:"businessDays",title:{pt:"Dias de trabalho",en:"Work days",es:"Días de trabajo"},desc:{pt:"Conte dias úteis entre duas datas.",en:"Count workdays between dates.",es:"Cuenta días laborables."}}
,{id:"temperatura-fahrenheit",slug:"temperatura-fahrenheit",icon:"🌡️",cat:"daily",type:"temperature",title:{pt:"Conversor Fahrenheit",en:"Fahrenheit converter",es:"Conversor Fahrenheit"},desc:{pt:"Converta Fahrenheit para outras escalas.",en:"Convert Fahrenheit to other scales.",es:"Convierte Fahrenheit."}}

];